name: First Workflow
on: workflow_dispatch
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print multi-line
        run: |
            echo "first line!"
            echo "second line!"
      - name: Output env variables
        run: |
            echo $GITHUB_SERVER_URL
            echo $GITHUB_REF
            echo $GITHUB_SHA
      - name: Print goodbye
        run: echo "Done - bye!"
      
